# 文件路径: .github/workflows/sync.yml

name: Sync with Upstream Repository

on:
  schedule:
    - cron: '0 2 * * *'

  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_FOR_SYNC }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Set up upstream remote
        run: |
          # 添加组内仓库作为上游远程
          git remote add upstream https://github.com/XidianSCgroup/TRUST.git

      - name: Fetch from upstream
        run: |
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --ff-only

      - name: Push changes to your fork
        run: |
          git push origin main